// <auto-generated />
using System;
using Limen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Limen.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Limen.Domain.Auth.AdminSession", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("IpAddress")
                    .HasColumnType("text");

                b.Property<DateTimeOffset?>("RevokedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("UserAgent")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ExpiresAt");

                b.HasIndex("Subject");

                b.ToTable("admin_sessions", (string)null);
            });

        modelBuilder.Entity("Limen.Domain.Nodes.Agent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("AgentVersion")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<DateTimeOffset>("EnrolledAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Hostname")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<Guid>("NodeId")
                    .HasColumnType("uuid");

                b.Property<string>("Platform")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<byte[]>("SecretHash")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.HasKey("Id");

                b.HasIndex("NodeId")
                    .IsUnique();

                b.ToTable("agents", (string)null);
            });

        modelBuilder.Entity("Limen.Domain.Nodes.Node", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset?>("LastSeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.PrimitiveCollection<string[]>("Roles")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.HasKey("Id");

                b.HasIndex("Status");

                b.ToTable("nodes", (string)null);
            });

        modelBuilder.Entity("Limen.Domain.Nodes.ProvisioningKey", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.PrimitiveCollection<string[]>("IntendedRoles")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<string>("KeyHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<Guid?>("ResultingNodeId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset?>("UsedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ExpiresAt");

                b.HasIndex("KeyHash")
                    .IsUnique();

                b.ToTable("provisioning_keys", (string)null);
            });

        modelBuilder.Entity("Limen.Domain.Tunnels.WireGuardPeer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AgentId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PublicKey")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset?>("RevokedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("TunnelIp")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("Id");

                b.HasIndex("AgentId");

                b.HasIndex("PublicKey")
                    .IsUnique();

                b.HasIndex("TunnelIp")
                    .IsUnique();

                b.ToTable("wireguard_peers", (string)null);
            });

        modelBuilder.Entity("Limen.Domain.Nodes.Agent", b =>
            {
                b.HasOne("Limen.Domain.Nodes.Node", null)
                    .WithOne("Agent")
                    .HasForeignKey("Limen.Domain.Nodes.Agent", "NodeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Limen.Domain.Nodes.Node", b =>
            {
                b.Navigation("Agent");
            });
#pragma warning restore 612, 618
    }
}
