/**
 * Limen.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateServiceCommandInternalPort } from './createServiceCommandInternalPort';


export interface CreateServiceCommand { 
    name: string;
    targetNodeId: string;
    containerName: string;
    internalPort: CreateServiceCommandInternalPort;
    image: string;
    autoDeploy: boolean;
}

